"""empty message

Revision ID: 2078081d182d
Revises: a1ef43ad20b3
Create Date: 2022-08-12 13:20:52.660908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2078081d182d'
down_revision = 'a1ef43ad20b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artist', ['facebook_link'])
    op.create_unique_constraint(None, 'artist', ['website'])
    op.create_unique_constraint(None, 'artist', ['phone'])
    op.drop_constraint('shows_artist_id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_venue_id_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'venue', ['venue_id'], ['id'])
    op.create_unique_constraint(None, 'venue', ['website'])
    op.create_unique_constraint(None, 'venue', ['image_link'])
    op.create_unique_constraint(None, 'venue', ['phone'])
    op.create_unique_constraint(None, 'venue', ['facebook_link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='unique')
    op.drop_constraint(None, 'venue', type_='unique')
    op.drop_constraint(None, 'venue', type_='unique')
    op.drop_constraint(None, 'venue', type_='unique')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_venue_id_fkey', 'shows', 'venue', ['venue_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('shows_artist_id_fkey', 'shows', 'artist', ['artist_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'artist', type_='unique')
    op.drop_constraint(None, 'artist', type_='unique')
    op.drop_constraint(None, 'artist', type_='unique')
    # ### end Alembic commands ###
