"""empty message

Revision ID: 30050a7e5440
Revises: 40c015830d68
Create Date: 2022-08-07 20:54:31.543671

"""
from xmlrpc.client import Boolean
from alembic import op
import sqlalchemy as sa
from datetime import date
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date

from app import venues


# revision identifiers, used by Alembic.
revision = '30050a7e5440'
down_revision = '40c015830d68'
branch_labels = None
depends_on = None

# Create an ad-hoc table to use for the insert statement.
area = table('area',
             column('id', Integer),
             column('state', String),
             column('city', String)
             )

genres = table('genres',
             column('name', String)
             )
genres = table('genres',
             column('name', String)
             )
genre_venue = table('genre_venue',
             column('name', String),
             column('venue_id', Integer)
             )
genre_artist = table('genre_artist',
             column('name', String),
             column('artist_id', Integer)
             )
venues = table('venues',
            column('id', Integer),
            column('area', Integer),
            column('name', String),
               column('address', String),
               column('phone', String),
               column('website', String),
               column('facebook_link', String),
               column('seeking_talent', Boolean),
               column('seeking_description', String),
               column('image_link', String)
            )

artists = table('artists',
               column('id', Integer),
               column('area', Integer),
               column('name', String),
               column('phone', String),
               column('facebook_link', String),
                column('seeking_venue', Boolean),
               column('image_link', String)
               )

shows = table('shows',
              column('venue_id', Integer),
              column('artist_id', Integer),
              column('start_time', Date)
               )
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
