"""empty message

Revision ID: 40c015830d68
Revises: 8c1f3d6d1597
Create Date: 2022-08-07 20:22:47.309090

"""
from alembic import op
import sqlalchemy as sa
from datetime import date
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date


# revision identifiers, used by Alembic.
revision = '40c015830d68'
down_revision = '8c1f3d6d1597'
branch_labels = None
depends_on = None

# Create an ad-hoc table to use for the insert statement.
area = table('area',
                       column('id', Integer),
                       column('state', String),
                        column('city', String)
                       )

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
    op.bulk_insert(area,
    [
        {'id': 1, 'state': 'AL', 'city':''},
        {'id': 2, 'state': 'AK', 'city': ''},
        {'id': 3, 'state': 'AZ', 'city': ''},
        {'id': 4, 'state': 'AR', 'city':''},
        {'id': 5, 'state': 'CA', 'city': 'San Francisco'},
        {'id': 6, 'state': 'CO', 'city': ''},
        {'id': 7, 'state': 'CT', 'city': ''},
        {'id': 8, 'state': 'DE', 'city': ''},
        {'id': 9, 'state': 'DC', 'city': ''},
        {'id': 10, 'state': 'FL', 'city': ''},
        {'id': 11, 'state': 'GA', 'city': ''},
        {'id': 12, 'state': 'HI', 'city': ''},
        {'id': 13, 'state': 'ID', 'city': ''},
        {'id': 14, 'state': 'ID', 'city': ''},
        {'id': 15, 'state': 'IL', 'city': ''},
        {'id': 16, 'state': 'IN', 'city': ''},
        {'id': 17, 'state': 'IA', 'city': ''},
        {'id': 18, 'state': 'KS', 'city': ''},
        {'id': 19, 'state': 'KY', 'city': ''},
        {'id': 20, 'state': 'LA', 'city': ''},
        {'id': 21, 'state': 'ME', 'city': ''},
        {'id': 22, 'state': 'MT', 'city': ''},
        {'id': 23, 'state': 'NE', 'city': ''},
        {'id': 24, 'state': 'NV', 'city': ''},
        {'id': 25, 'state': 'NH', 'city': ''},
        {'id': 26, 'state': 'NJ', 'city': ''},
        {'id': 27, 'state': 'NM', 'city': ''},
        {'id': 28, 'state': 'NY', 'city': 'New York'},
        {'id': 29, 'state': 'NC', 'city': ''},
        {'id': 30, 'state': 'ND', 'city': ''},
        {'id': 31, 'state': 'OH', 'city': ''},
        {'id': 32, 'state': 'OK', 'city': ''},
        {'id': 33, 'state': 'OR', 'city': ''},
        {'id': 34, 'state': 'MD', 'city': ''},
        {'id': 35, 'state': 'MA', 'city': ''},
        {'id': 36, 'state': 'MA', 'city': ''},
        {'id': 37, 'state': 'MI', 'city': ''},
        {'id': 38, 'state': 'MN', 'city': ''},
        {'id': 39, 'state': 'MS', 'city': ''},
        {'id': 40, 'state': 'MO', 'city': ''},
        {'id': 41, 'state': 'PA', 'city': ''},
        {'id': 42, 'state': 'RI', 'city': ''},
        {'id': 43, 'state': 'SC', 'city': ''},
        {'id': 44, 'state': 'SD', 'city': ''},
        {'id': 45, 'state': 'TN', 'city': ''},
        {'id': 46, 'state': 'TX', 'city': ''},
        {'id': 47, 'state': 'UT', 'city': ''},
        {'id': 48, 'state': 'VT', 'city': ''},
        {'id': 49, 'state': 'VA', 'city': ''},
        {'id': 50, 'state': 'WA', 'city': ''},
        {'id': 51, 'state': 'WV', 'city': ''},
        {'id': 52, 'state': 'WI', 'city': ''},
        {'id': 53, 'state': 'WY', 'city': ''},
    ]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
