"""empty message

Revision ID: 8c1f3d6d1597
Revises: c32651233539
Create Date: 2022-08-07 19:39:23.924602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1f3d6d1597'
down_revision = 'c32651233539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('area', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
    # op.bulk_insert(accounts_table,
    #                [
    #                    {'id': 1, 'name': 'AL', 'city':NULL},
    #                    {'id': 2, 'name': 'AK', 'city': NULL},
    #                    {'id': 3, 'name': 'AZ', 'city': NULL},
    #                    {'id': 4, 'name': 'AR', 'city':NULL},
    #                    {'id': 5, 'name': 'CA', 'city': 'San Francisco'},
    #                    {'id': 6, 'name': 'CO', 'city': NULL},
    #                    {'id': 7, 'name': 'CT', 'city': NULL},
    #                    {'id': 8, 'name': 'DE', 'city': NULL},
    #                    {'id': 9, 'name': 'DC', 'city': NULL},
    #                    {'id': 10, 'name': 'FL', 'city': NULL},
    #                    {'id': 11, 'name': 'GA', 'city': NULL},
    #                    {'id': 12, 'name': 'HI', 'city': NULL},
    #                    {'id': 13, 'name': 'ID', 'city': NULL},
    #                    {'id': 14, 'name': 'ID', 'city': NULL},
    #                    {'id': 15, 'name': 'IL', 'city': NULL},
    #                    {'id': 16, 'name': 'IN', 'city': NULL},
    #                    {'id': 17, 'name': 'IA', 'city': NULL},
    #                    {'id': 18, 'name': 'KS', 'city': NULL},
    #                    {'id': 19, 'name': 'KY', 'city': NULL},
    #                    {'id': 20, 'name': 'LA', 'city': NULL},
    #                    {'id': 21, 'name': 'ME', 'city': NULL},
    #                    {'id': 22, 'name': 'MT', 'city': NULL},
    #                    {'id': 23, 'name': 'NE', 'city': NULL},
    #                    {'id': 24, 'name': 'NV', 'city': NULL},
    #                    {'id': 25, 'name': 'NH', 'city': NULL},
    #                    {'id': 26, 'name': 'NJ', 'city': NULL},
    #                    {'id': 27, 'name': 'NM', 'city': NULL},
    #                    {'id': 28, 'name': 'NY', 'city': 'New York'},
    #                    {'id': 29, 'name': 'NC', 'city': NULL},
    #                    {'id': 30, 'name': 'ND', 'city': NULL},
    #                    {'id': 31, 'name': 'OH', 'city': NULL},
    #                    {'id': 32, 'name': 'OK', 'city': NULL},
    #                    {'id': 33, 'name': 'OR', 'city': NULL},
    #                    {'id': 34, 'name': 'MD', 'city': NULL},
    #                    {'id': 35, 'name': 'MA', 'city': NULL},
    #                    {'id': 36, 'name': 'MA', 'city': NULL},
    #                    {'id': 37, 'name': 'MI', 'city': NULL},
    #                    {'id': 38, 'name': 'MN', 'city': NULL},
    #                    {'id': 39, 'name': 'MS', 'city': NULL},
    #                    {'id': 40, 'name': 'MO', 'city': NULL},
    #                    {'id': 41, 'name': 'PA', 'city': NULL},
    #                    {'id': 42, 'name': 'RI', 'city': NULL},
    #                    {'id': 43, 'name': 'SC', 'city': NULL},
    #                    {'id': 44, 'name': 'SD', 'city': NULL},
    #                    {'id': 45, 'name': 'TN', 'city': NULL},
    #                    {'id': 46, 'name': 'TX', 'city': NULL},
    #                    {'id': 47, 'name': 'UT', 'city': NULL},
    #                    {'id': 48, 'name': 'VT', 'city': NULL},
    #                    {'id': 49, 'name': 'VA', 'city': NULL},
    #                    {'id': 50, 'name': 'WA', 'city': NULL},
    #                    {'id': 51, 'name': 'WV', 'city': NULL},
    #                    {'id': 52, 'name': 'WI', 'city': NULL},
    #                    {'id': 53, 'name': 'WY', 'city': NULL},
    #                ]
    #                )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('area', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
